version: "3.9"

services:
  front:
    image: sermalenk/skypro-front:lesson-38
    ports:
      - 80:80
    depends_on:
      - api

  api:
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    image: ekurochkin/calendar_ekurochkin_app
    ports:
      - 8000:8000
    depends_on:
      pg:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    volumes:
      - ./.env:/app/.env

  bot:
    build:
      context: .
    restart: always
    depends_on:
      migrations:
        condition: service_completed_successfully
      pg:
        condition: service_healthy
    command: python ./todolist/manage.py
    volumes:
      - ./.env:/app/.env

  migrations:
    build:
      context: .
    image: ekurochkin/calendar_ekurochkin_app
    volumes:
      - ./.env:/app/.env
    depends_on:
      pg:
        condition: service_healthy
#    command: python ./todolist/manage.py m igrate
    env_file:
      - .env
    command: python ./todolist/manage.py migrate

  pg:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    env_file:
      - .env
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

