# Generated by Django 4.0.1 on 2022-12-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(verbose_name='id чата')),
                ('user_ud', models.BigIntegerField(verbose_name='пользовательский идентификатор')),
                ('verification_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Код верификации')),
            ],
        ),
    ]
